# Generated by Django 6.0.7 on 2026-07-30 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridorLogistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points_depart_arrivee', models.CharField(max_length=200)),
                ('carte', models.ImageField(blank=True, null=True, upload_to='corridors/')),
            ],
        ),
        migrations.CreateModel(
            name='OpportuniteSousTraitance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('secteur', models.CharField(choices=[('mines', 'Mines'), ('logistique', 'Logistique & Transport'), ('maintenance', 'Maintenance industrielle'), ('rse', 'RSE & Développement communautaire'), ('energie', 'Énergie'), ('eau', 'Eau'), ('telecoms', 'Télécommunications'), ('autre', 'Autre')], max_length=50)),
                ('localisation', models.CharField(max_length=200)),
                ('entreprise_donneur_ordre', models.CharField(max_length=200)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField()),
                ('budget_indicatif', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('document_appel_offre', models.FileField(blank=True, null=True, upload_to='appels_offres/')),
            ],
        ),
        migrations.CreateModel(
            name='OffreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_service', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_telephone', models.CharField(max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='soustraitance.corridorlogistique')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres_services', to='pme.pme')),
            ],
        ),
    ]
