# Generated by Django 6.0.7 on 2026-07-30 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0002_candidat_user'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('secteur_activite', models.CharField(max_length=200)),
                ('date_creation', models.DateField()),
                ('statut_arsp', models.CharField(choices=[('non_demande', 'Non demandée'), ('en_attente', 'En attente de validation'), ('obtenue', 'Attestation obtenue'), ('refusee', 'Refusée')], default='non_demande', max_length=20)),
                ('numero_arsp', models.CharField(blank=True, max_length=100, null=True)),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='business_plans/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_pme/')),
                ('site_web', models.URLField(blank=True, null=True)),
                ('email_contact', models.EmailField(max_length=254)),
                ('telephone_contact', models.CharField(max_length=20)),
                ('visible_catalogue', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cohorte_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programmes.cohorte')),
                ('fondateurs', models.ManyToManyField(related_name='pmes_creees', to='candidatures.candidat')),
            ],
            options={
                'verbose_name': 'PME',
                'verbose_name_plural': 'PMEs',
            },
        ),
    ]
