# Generated by Django 6.0.7 on 2026-07-30 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_candidats_prevus', models.PositiveIntegerField(default=50)),
                ('nombre_femmes_min', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('focus_minier', models.TextField()),
                ('specialisation_pedagogique', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('intitule', models.CharField(max_length=255)),
                ('focalisation_technique', models.TextField()),
                ('livrable', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('chef_lieu', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='DemoDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('jury_membres', models.TextField()),
                ('cohorte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programmes.cohorte')),
            ],
        ),
        migrations.AddField(
            model_name='cohorte',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.hub'),
        ),
        migrations.CreateModel(
            name='ProgrammeGCL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Génération Contenu Local 2026', max_length=255)),
                ('description', models.TextField()),
                ('duree_jours', models.PositiveSmallIntegerField(default=23)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('objectif_general', models.TextField()),
                ('modules', models.ManyToManyField(related_name='programmes', to='programmes.moduleformation')),
            ],
        ),
        migrations.AddField(
            model_name='cohorte',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programmegcl'),
        ),
        migrations.AddField(
            model_name='hub',
            name='province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programmes.province'),
        ),
        migrations.AlterUniqueTogether(
            name='cohorte',
            unique_together={('programme', 'hub', 'date_debut')},
        ),
    ]
