# Generated by Django 6.0.7 on 2026-07-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0002_candidat_user'),
        ('pme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuichetInvestissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('soutenir_projet', 'Soutenir un Projet (Amorçage & Prototypage)'), ('investir_pme', 'Investir dans une sPME (Capital-Développement)'), ('seed_fund', 'Le GCL Seed Fund (Grands Bailleurs)')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('type_investisseur', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('institution', 'Institution/Bailleur')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpportuniteInvestissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('montant_recherche', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites_investissement', to='candidatures.candidat')),
                ('guichet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investissement.guichetinvestissement')),
                ('pme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunites_investissement', to='pme.pme')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('initiee', 'Initiée'), ('en_attente', 'En attente de validation'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='initiee', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('investisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investissement.investisseur')),
                ('opportunite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investissement.opportuniteinvestissement')),
            ],
        ),
    ]
