# Generated by Django 6.0.7 on 2026-07-30 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0002_candidat_user'),
        ('pme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreprisePublique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('sigle', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('secteur', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_ep/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefiTechnologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domaine', models.CharField(max_length=200)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours de résolution'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('budget_indicatif', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis', to='portefeuille.entreprisepublique')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_solution', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fichier_presentation', models.FileField(blank=True, null=True, upload_to='solutions/')),
                ('contact_nom', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_evaluation', 'En évaluation'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='soumise', max_length=20)),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='candidatures.candidat')),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='portefeuille.defitechnologique')),
                ('pme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='pme.pme')),
            ],
        ),
    ]
