# Generated by Django 6.0.7 on 2026-07-30 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComiteSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='comite_logos/')),
                ('representant_nom', models.CharField(max_length=200)),
                ('representant_email', models.EmailField(max_length=254)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConseilSages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=300)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='conseil_sages/')),
                ('biographie', models.TextField()),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AuditRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_publication', models.DateField()),
                ('fichier_pdf', models.FileField(upload_to='audits/')),
                ('resume', models.TextField()),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='ethique.comitesurveillance')),
            ],
        ),
    ]
