# Generated by Django 6.0.7 on 2026-07-30 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(default='Congolaise', max_length=50)),
                ('province_residence', models.CharField(max_length=100)),
                ('diplome', models.CharField(max_length=100)),
                ('etablissement', models.CharField(max_length=200)),
                ('domaine_etude', models.CharField(max_length=100)),
                ('experience_professionnelle', models.TextField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DossierCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField()),
                ('note_intention', models.TextField(help_text='Description du projet entrepreneurial (1 page)')),
                ('cv', models.FileField(upload_to='cv/')),
                ('diplome_fichier', models.FileField(upload_to='diplomes/')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('preselectionne', 'Présélectionné'), ('entretien', 'Entretien programmé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='soumis', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('commentaire_evaluateur', models.TextField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='candidatures.candidat')),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='programmes.cohorte')),
            ],
            options={
                'unique_together': {('candidat', 'cohorte')},
            },
        ),
    ]
