# Generated by Django 6.0.7 on 2026-07-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0002_candidat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiercandidature',
            name='prototype',
            field=models.FileField(blank=True, null=True, upload_to='prototypes/'),
        ),
    ]
